### PR TITLE
CI

### PR DESCRIPTION
**Pull request by pschmitt**
Current state:

- A whole lof of containers are getting built! Their main purpose is to quickly test zinit against (older) zsh versions. So they essentially contain zsh and zinit. There are a few helper functions available inside it (`zinit::<tab>`). I've mainly focussed on the alpine-based container for now.
- Tests are getting run. But none of them pass... They all need to be updated since they were written in the zplugin days.
- Docs are getting generated and the build is set to fail if there are not up to date. This isn't exactly working as expected though since the generated docs seem to not be generated in reproducible way (To be debugged further)

Here's what is interesting to look at: 
- CI logs: https://github.com/pschmitt/zinit/actions
- Containers that are being built: https://github.com/pschmitt/zinit/pkgs/container/zinit 
- `docker run -it --rm ghcr.io/pschmitt/zinit:latest`

Refs:
- #36
- #37
- https://github.com/zdharma-continuum/zinit/discussions/21
- https://github.com/zdharma-continuum/zinit/blob/bef57e843d0d8c239fcb208cc0576216c683f788/.travis.yml#L26-L35

### CODE REVIEW

**Comment by pschmitt** [comment]
Superseded (partially) by #70

**Comment by pschmitt** [comment]
Partially superseded by #117 as well.

**Comment by pschmitt** [comment]
The only feature that's left here that's not already in the main branch is the "make test" bit that's broken (the tests are, not the CI part of it)

**Comment by vladdoster** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
