### PR TITLE
Fix #396

### LINKED ISSUE #396: [feat]: Use different context for zinit completion
### If the feature request is for a plugin or theme, specify it here.

_No response_

### If the feature solves a problem you have, specify it here.

_No response_

### Describe the proposed feature.

Screenshot from 2022-10-15 14-01-57

As the figure, zinit's context should be `zinit-cd` not simple `zinit`, just like `git-add`.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Related Issues

_No response_

### PR DESCRIPTION
**Pull request by Freed-Wu**
## Description 

Now the context is correct.

```sh
❯ zinit cd <C-X>h
tags in context :completion::complete:zinit::
    argument-rest  (_arguments _zinit)
tags in context :completion::complete:zinit-cd::
    dsnippets lsnippets plugins  (_zinit)
```

## Motivation and Context 

Use can use different context to `zstyle` some different behaviour.

## Related Issue(s) 

Fix #396

## Types of changes 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist: 

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by vladdoster** [comment]
I don't quite understand the fix here. Could you elaborate?

**Comment by Freed-Wu** [comment]
Before:

```
❯ zinit cd fzf-tab-source
tags in context :completion::complete:zinit::
    argument-rest  (_arguments _zinit)
tags in context :completion::complete:zinit:argument-rest:
    dsnippets lsnippets plugins  (_zinit)
❯ zinit edit
tags in context :completion::complete:zinit::
    argument-rest  (_arguments _zinit)
tags in context :completion::complete:zinit:argument-rest:
    dsnippets lsnippets plugins  (_zinit)
```

After

```
❯ zinit cd fzf-tab-source
tags in context :completion::complete:zinit::
    argument-rest  (_arguments _zinit)
tags in context :completion::complete:zinit-cd::
    dsnippets lsnippets plugins  (_zinit)
❯ zinit edit
tags in context :completion::complete:zinit::
    argument-rest  (_arguments _zinit)
tags in context :completion::complete:zinit-edit:
    dsnippets lsnippets plugins  (_zinit)
```

It allows user customize different behaviour in different context.

**Comment by vladdoster** [comment]
Can you rebase your branch onto main so the checks will pass?

**Comment by Freed-Wu** [comment]
OK.

**Comment by Freed-Wu** [comment]
All tests passed.

**Comment by Freed-Wu** [comment]
Is any other problem? @vladdoster

**Comment by Freed-Wu** [comment]
@pschmitt

**Comment by Freed-Wu** [comment]
@vladdoster @pschmitt

**Comment by vladdoster** [comment]
@Freed-Wu, 

Resolve merge conflicts and I will merge.

**Comment by Freed-Wu** [comment]
<https://github.com/zdharma-continuum/zinit/blob/main/_zinit#L366> has fixed.

**Pull request closed without merging**
