### PR TITLE
Update default branch from `master` to `main`

### PR DESCRIPTION
**Pull request by pschmitt**
Hundred ~~PRs! 🤯~~ issues! :rofl: 

Refs:
- #46
- #36 

**:warning:  After this is merged we need to RENAME the master branch!**
**:boom: This needs to be done via the UI, otherwise the URLs pointing to /master won't be redirected**
https://github.com/zdharma-continuum/zinit/settings/branches

### CODE REVIEW

**Review by alichtman — APPROVED** [review]
I'll let you handle the migration entirely (renaming the branches). LGTM

**Comment by pschmitt** [comment]
Okay, let's do this!

**Comment by pschmitt** [comment]
image

**Comment by pschmitt** [comment]
image

**Comment by pschmitt** [comment]
Dedicated wiki entry:

https://github.com/zdharma-continuum/zinit/wiki/New-main-branch

**Pull request merged**
