### PR TITLE
‼ jq ftw

### PR DESCRIPTION
**Pull request by pschmitt**
# ⚠ JSON parsing using jq

Got rid of the very awkward in-house custom JSON parsing. The API stays more of less the same.

## This is the breaking change

**zinit requires `jq`! (only for the `pack` ice)**

## Also included

- local packages.json files can now be loaded via absolute paths (relative ones already worked) or **other repositories**
- `zinit pack ver"my-branch" for mypackage` works now as intended (the `ver` ice)
- `file://` URLs are now supported by `.zinit-download-file-stdout`. They kinda already were, provided you had `curl`or `lynx` installed (ie. not `wget`)

### CODE REVIEW

**Review by alichtman — APPROVED** [review]
Love this, UNIX philosophy and all.

**Comment by pschmitt** [comment]
Once this and #112 land we can get some real ci going for the packages :)

**Comment by alichtman** [comment]
Feel free to ship whenever

**Comment by pschmitt** [comment]
Okay, here we go!

**Comment by vladdoster** [comment]
yeah this is a great change, thanks for implementing this.

**Pull request merged**
