### PR TITLE
Revert "(bugfix): update bpick regex groups"

### PR DESCRIPTION
**Pull request by AndrewDaws**
Reverts zdharma-continuum/zinit#158

As noted in issue #160 and pull request #158, this broke Linux application selection.

### CODE REVIEW

**Comment by vladdoster** [comment]
Closing in favor of #162

**Comment by gaerfield** [comment]
Why was this closed again?
Main is broken and self-update seems not to allow to pin a version. Reverting the main branch to be stable while improving the original feature and doing code-review and follow-up refinements without any pressure seems to be a valid approach.
Instead the main is broken for a week now.

**Review by alichtman — APPROVED** [review]

**Comment by alichtman** [comment]
You're right -- we can't ever break the main branch.

**Comment by vladdoster** [comment]
This goes back to breaking mac-os binary selections.

**Comment by AndrewDaws** [comment]
> This goes back to breaking mac-os binary selections.

@vladdoster I investigated _all_ the commits made to the `zinit-install.zsh` file (I stopped after going back a year), and the only other changes made to that selection of code was your commit 2 months ago, b10e1c5fdcef3f77d6c46cbaf96e5c0b0ddc1a32, when you added `macos` as another search term for darwin. So for at least a year, that selection has _been_ broken for darwin in some way, so it's **NOT** a new development.

Should selection be fixed for darwin/mac-os?
YES! 100% it should be fixed. But it should **NOT**, nor ever be at the cost of breaking systems that had been working (nearly) perfectly for at least a year, if not more.

The moment this was reported as an issue, it should have been reverted so it could get back to a working state, then the changes could be worked on more until it was reviewed and shown to not break other things. The fact it was left in a broken state _AND_ this pull request closed without a fix or reverting is completely unacceptable.

I, and everyone else, are eternally grateful for the hard work and time people put in to open source projects like this, and certainly know I would not want it all to be dependent on me.

I just seriously worry about the health and longevity of this project if potentially breaking changes can be made and merged in by a single person without requiring either a completed review from someone else or at least some time passed to give others a chance to try and review. Let alone issues/pull requests addressing issues being closed for said issues.

Is there the possibility that someone still doesn't review a change?
Of course! That's an unfortunate downside of comparatively small projects like this, but at least people have a chance to make sure it doesn't break.

We don't need a repeat of psprint in which we are all at the fate of one person making rash decisions and changes that affect all users. I thought the whole point of making this more of a community-based project was to avoid exactly that issue.

**Comment by AndrewDaws** [comment]
I should probably clarify that I do not want any witch hunts, fingers being pointed, or any drama. Since none of that ever helps.


I certainly know I break things at work and also fix things other people break. Bugs are a natural part of software development and engineering.

The important part though is that everyone acts professionally and things get fixed in some way shape or form (doesn't matter who!). Which fundamentally is all anyone actually cares about.

Avoiding bugs as much as possible, and fixing them when they inevitably they occur.

**Pull request merged**
