### PR TITLE
`zinit pack`: Support alternative sources

### PR DESCRIPTION
**Pull request by pschmitt**
- Allow installation from local packages.json files or other repositories
- 2 new env vars users can override: 
  - `ZINIT[PACKAGE_REPO]=zhdarma-continuum/zinit-packages`
  - `ZINIT[PACKAGE_BRANCH]=HEAD`

Installation of local packages: `zinit pack for local/path/to/my/package.json`

Refs:
- https://github.com/zdharma-continuum/zinit-packages/pull/2

### CODE REVIEW

**Comment by alichtman** [comment]
My understanding of this addition is that it would be used by forking the packages repo, and add my own packages to it.

Maybe we could mention the things in the Changelog in the wiki?

**Review by alichtman — APPROVED** [review]

**Comment by pschmitt** [comment]
> My understanding of this addition is that it would be used by forking the packages repo, and add my own packages to it.

Correct.

> Maybe we could mention the things in the Changelog in the wiki?

The wiki is imo a better place for that.

**Comment by alichtman** [comment]
> The wiki is imo a better place for that.

Agreed, a clearer way to explain what I was saying is: Maybe we could mention this feature + provide usage guidelines in the wiki?

**Comment by pschmitt** [comment]
Closing in favor of #116

**Comment by pschmitt** [comment]
BTW zinit supported installs of local packages all along :see_no_evil:
Only relative paths were supported though.

**Pull request closed without merging**
