### PR TITLE
refactor: zunit tests & `gh-r` logic

### PR DESCRIPTION
**Pull request by vladdoster**
## Changelog:

- Ability to run unit tests without Docker
- Define a Z-unit \_support/bootstrap script defining the isolated test
  environment in a temp dir via `mktemp -d`, to ensure a clean test environment.
- GH actions workflow now tests macOS & Windows and bumps Ubuntu to the latest.
- GH actions workflow leverages Homebrew to simplify installing zsh & zunit
- Condense Z-unit GH workflow into more organized build matrix. It avoids
  creating a new environment per test file as some test files only have one or
  two tests.
- Change or remove logic in the `setup` and `teardown` functions to commands
  which apply to type of tests being run (e.g., `gh-r` setup sets defualt ice
  `gh-r` and `nocompile`).
- Expand tests for testing `gh-r` on Linux & macOS for ensuring correct release
  selection.
- Correct GH workflow `on` conditions to avoid duplicating jobs.
- Update `gh-r` ice logic to be smarter about selecting a release for the
  current system.
- Expand linting to include the tools `shfmt`, `shellcheck`, and `mdformat`
- Rudimentary testing for all Zinit annexes (e.g., install with no errors)

### test numbers:

|   Test   | Before | Now |
| :------: | :----: | :-: |
| annexes  |   3    | 10  |
|   gh-r   |   3    | 95  |
| plugins  |   2    |  3  |
| snippets |   4    |  4  |

Screen Shot 2022-04-23 at 21 57 08

### CODE REVIEW

**Comment by pschmitt** [comment]
I don't believe that running tests outside of the container is such a good idea, IMO this will only lead to headaches down the line as in "the tests pass on MY machine".

**Comment by vladdoster** [comment]
> I don't believe that running tests outside of the container is such a good idea, IMO this will only lead to headaches down the line as in "the tests pass on MY machine".

Running tests in docker doesn't make sense. If a user is on macOS and the tests are $OSTYPE of `linux-gnu`, then the tests are useless. 

Documentation generation makes sense to isolate since it generates something, but the tests don't.

**Comment by pschmitt** [comment]
Yeah, right. My idea was to override the `MACHTYPE`, `OSTYPE` vars instead, which in retrospect isn't a great idea. You are right!

**Comment by pschmitt** [comment]
Please don't remove the emojis from the job titles. I purposely added these. It makes it easier to quickly see what job failed or whatever. You may hate them but they do serve a purpose. And it's out of context.

**Comment by vladdoster** [comment]
Test these changes with the following snippet:

```bash
#!/usr/bin/env zsh
#=== HELPER METHODS ===================================
function error() { print -P "%F{160}[ERROR] ---%f%b $1" >&2 && exit 1; }
function info() { print -P "%F{34}[INFO] ---%f%b $1"; }
#=== ZINIT ============================================
# GIT_REPO=$(git rev-parse --show-toplevel)/tests/_support/zinit
GIT_REPO=$(mktemp -d)/zinit
if [[ -d $GIT_REPO ]]; then
  rm -rf $GIT_REPO
fi
typeset -gAH ZINIT;
ZINIT[HOME_DIR]=$GIT_REPO  ZPFX=$ZINIT[HOME_DIR]/polaris
ZINIT[BIN_DIR]=$ZINIT[HOME_DIR]/zinit.git ZINIT[OPTIMIZE_OUT_DISK_ACCESSES]=1
ZINIT[COMPLETIONS_DIR]=$ZINIT[HOME_DIR]/completions ZINIT[SNIPPETS_DIR]=$ZINIT[HOME_DIR]/snippets
ZINIT[ZCOMPDUMP_PATH]=$ZINIT[HOME_DIR]/zcompdump    ZINIT[PLUGINS_DIR]=$ZINIT[HOME_DIR]/plugins
ZI_REPO='zdharma-continuum'; GH_RAW_URL='https://raw.githubusercontent.com'
info 'Downloading Zinit' \
  && command git clone \
      --branch 'refactor/zunit-tests' \
      https://github.com/$ZI_REPO/zinit.git \
      $ZINIT[BIN_DIR] \
  || error 'Unable to download zinit' \
  && info 'Installing Zinit' \
  && command chmod g-rwX $ZINIT[HOME_DIR] \
  && zcompile $ZINIT[BIN_DIR]/zinit.zsh \
  && info 'Successfully installed Zinit' \
  || error 'Unable to install Zinit'
source $ZINIT[BIN_DIR]/zinit.zsh \
  && autoload -Uz _zinit \
  && (( ${+_comps} )) \
  && _comps[zinit]=_zinit
#=== Plugins, Snippets, etc. below
```

**Comment by sm1999** [comment]
@vladdoster Excellent work!

Can you please keep `bpick` ice. some programs have different variants of release. e.g. [nnn](https://github.com/jarun/nnn/releases/)
`bpick` is helpful for selecting which variant to download.

**Comment by vladdoster** [comment]
> @vladdoster Excellent work!
> 
> Can you please keep `bpick` ice. some programs have different variants of release. e.g. [nnn](https://github.com/jarun/nnn/releases/) `bpick` is helpful for selecting which variant to download.

Whoops, didn't realize I had removed bpick logic. Have added it back in commit [c55400531dfe471230e99b13cef009fddbc642d5](https://github.com/zdharma-continuum/zinit/pull/201/commits/c55400531dfe471230e99b13cef009fddbc642d5).

**Comment by vladdoster** [comment]
Cuts time dramatically of workflows while expanding systems tested

E.g., Linting

## Before - One version of Ubuntu took 7 minutes:


Screen Shot 2022-04-09 at 07 20 42


## After - 2 versions of macOS & Ubuntu took 1 minute and 30 seconds:

Screen Shot 2022-04-09 at 07 21 14

**Comment by seagle0128** [comment]
It seems fzf binary is still incorrect on M1 chip. I've reported #287 .

**Pull request merged**
