### PR TITLE
[DNM] testing: zshelldocs generation bug

### PR DESCRIPTION
**Pull request by vladdoster**
Signed-off-by: Vladislav Doster <mvdoster@gmail.com>

### CODE REVIEW

**Comment by alichtman** [comment]
Why is this changeset so large? I'm expecting a < 10 line change here.

**Review by alichtman — CHANGES_REQUESTED** [review]
Drop / separate doc changes

**Comment by vladdoster** [comment]
@alichtman This is me just testing for #176 

Thought I had it on draft :/

**Comment by vladdoster** [comment]
Closed in favor of #200

**Pull request closed without merging**
