### PR TITLE
Add a new ice named "link", enabling local snippets to be symlinked instead of copied into the cache.

### PR DESCRIPTION
**Pull request by twang817**
## Description

Add a new ice named "link", enabling local snippets to be symlinked instead of copied into the cache.

## Motivation and Context

For those of us who keep our entire dotfiles in a git repo (dotbare, etc.), we often want to treat many of our rc files as snippets that can be managed by zinit. This is great for taking advantage of features such as trigger-load, if, or has ices. I used to use local plugins for this but noticed that the load times for plugins were significantly longer than snippets.

In migrating to snippets, I found that copying files from a source path into the ZINIT_SNIPPETS directory meant that I had to run zinit update [snippet] for any changes that I may make to my rc files to take effect. This ice replaces the cp command with ln, which instantly reflects changes with a new shell. I thought that snippets, in combination with symlinks, are an effective way to manage a lot of low-level rc file stuff that doesn't necessarily need to be in a separate git repository of its own.

## Usage examples

Given:
```
$ cat ~/.dotfiles/zsh/aliases/general.zsh
alias ls=' ls --color=tty --group-directories-first'
alias ll='ls -lFh'
alias l='ll'
alias la='ll -A'
alias lt='ll -t'
alias lr='ll -R'
alias ltr='ll -tr'
```

In your zshrc:
```zsh
zinit light-mode is-snippet link for \
    id-as'aliases-general' \
        ~/.dotfiles/zsh/aliases/general.zsh \
```

The 'aliases-general' snippet will be symlinked in the zinit snippet dir:

```
~/.dotfiles/zsh/_snippets/aliases-general $ ls -l
lrwxr-xr-x   26 user 27 Dec  2021 aliases-general -> ../../aliases/_general.zsh
```

Load times are much improved:
```
Plugin loading times:
 -104 ms     3 ms - aliases-general
```

## How Has This Been Tested?

Tests included in PR; I've been using this for months.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by twang817** [comment]
Replaces #150

**Comment by vladdoster** [comment]
I'm not sure what part of the wiki you're talking about..? The GitHub pages haven't been touched since December.

**Comment by vladdoster** [comment]
Did you have any issues generating the docs via `make docs`?

**Comment by vladdoster** [comment]
Looks like the zunit test you added needs to be tweaked. I think this might help 

https://github.com/zulu-zsh/zulu/blob/master/tests/commands/bundle.zunit

**Comment by twang817** [comment]
Yeah, I'm working on it.

I'm not sure why lint is failing.  I see it passing on other PRs, but when I run mdformat locally, I get failures with README.md even without my changes (ie, on main).

**Comment by vladdoster** [comment]
try this?

```zsh
python3 -m pip install --user \
    linkify-it-py \
    mdformat{'','-config','-gfm','-shfmt','-tables',-toc'} \
&& find . -name '*.md' -type f -print0 | xargs -0 -n1 -P4 python3 -m mdformat --check --wrap 120
```

**Comment by vladdoster** [comment]
```zsh
vlad@media-server ~/.local/share/zsh/zinit/zinit.git main
ᐳ python3 -m pip install --user \
    linkify-it-py \
    mdformat{'','-config','-gfm','-shfmt','-tables','-toc'} \
&& find . -name '*.md' -type f -print0 | xargs -0 -n1 -P4 python3 -m mdformat --check --wrap 120
Requirement already satisfied: linkify-it-py in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (1.0.3)
Requirement already satisfied: mdformat in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (0.7.14)
Requirement already satisfied: mdformat-config in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (0.1.3)
Requirement already satisfied: mdformat-gfm in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (0.3.5)
Requirement already satisfied: mdformat-shfmt in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (0.1.0)
Requirement already satisfied: mdformat-tables in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (0.4.1)
Requirement already satisfied: mdformat-toc in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (0.3.0)
Requirement already satisfied: uc-micro-py in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from linkify-it-py) (1.0.1)
Requirement already satisfied: tomli>=1.1.0 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from mdformat) (2.0.1)
Requirement already satisfied: markdown-it-py<3.0.0,>=1.0.0b2 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from mdformat) (2.0.1)
Requirement already satisfied: importlib-metadata>=3.6.0 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from mdformat) (4.11.3)
Requirement already satisfied: ruamel.yaml>=0.16.0 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from mdformat-config) (0.17.21)
Requirement already satisfied: toml>=0.10.0 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from mdformat-config) (0.10.2)
Requirement already satisfied: mdit-py-plugins<0.4.0,>=0.2.0 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from mdformat-gfm) (0.3.0)
Requirement already satisfied: zipp>=0.5 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from importlib-metadata>=3.6.0->mdformat) (3.8.0)
Requirement already satisfied: mdurl~=0.1 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from markdown-it-py<3.0.0,>=1.0.0b2->mdformat) (0.1.0)
Requirement already satisfied: attrs<22,>=19 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from markdown-it-py<3.0.0,>=1.0.0b2->mdformat) (21.4.0)
Requirement already satisfied: ruamel.yaml.clib>=0.2.6 in /home/linuxbrew/.linuxbrew/lib/python3.9/site-packages (from ruamel.yaml>=0.16.0->mdformat-config) (0.2.6)

vlad@media-server ~/.local/share/zsh/zinit/zinit.git main
```

**Comment by vladdoster** [comment]
Could the [gh-pages branch](https://github.com/zdharma-continuum/zinit/tree/gh-pages) be what you're looking for?

**Comment by twang817** [comment]
> Could the [gh-pages branch](https://github.com/zdharma-continuum/zinit/tree/gh-pages) be what you're looking for?

This used to be in markdown format and used a docs generator (I don't know which one, but something like Sphinx).  All I see in gh-pages are now the generated html site.  Did we change to maintaining raw HTML for the site?

**Comment by twang817** [comment]
> vlad@media-server ~/.local/share/zsh/zinit/zinit.git main

Not much luck:

```
❯ python3 -m pip install --user \
    linkify-it-py \
    mdformat{'','-config','-gfm','-shfmt','-tables','-toc'} \
&& find . -name '*.md' -type f -print0 | xargs -0 -n1 -P4 python3 -m mdformat --check --wrap 120
Requirement already satisfied: linkify-it-py in /Users/twang817/.local/lib/python3.8/site-packages (1.0.3)
Requirement already satisfied: mdformat in /Users/twang817/.local/lib/python3.8/site-packages (0.7.14)
Requirement already satisfied: mdformat-config in /Users/twang817/.local/lib/python3.8/site-packages (0.1.3)
Requirement already satisfied: mdformat-gfm in /Users/twang817/.local/lib/python3.8/site-packages (0.3.5)
Requirement already satisfied: mdformat-shfmt in /Users/twang817/.local/lib/python3.8/site-packages (0.1.0)
Requirement already satisfied: mdformat-tables in /Users/twang817/.local/lib/python3.8/site-packages (0.4.1)
Requirement already satisfied: mdformat-toc in /Users/twang817/.local/lib/python3.8/site-packages (0.3.0)
Requirement already satisfied: uc-micro-py in /Users/twang817/.local/lib/python3.8/site-packages (from linkify-it-py) (1.0.1)
Requirement already satisfied: tomli>=1.1.0 in /Users/twang817/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from mdformat) (1.2.2)
Requirement already satisfied: importlib-metadata>=3.6.0 in /Users/twang817/.local/lib/python3.8/site-packages (from mdformat) (4.11.3)
Requirement already satisfied: markdown-it-py<3.0.0,>=1.0.0b2 in /Users/twang817/.local/lib/python3.8/site-packages (from mdformat) (2.1.0)
Requirement already satisfied: ruamel.yaml>=0.16.0 in /Users/twang817/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from mdformat-config) (0.17.20)
Requirement already satisfied: toml>=0.10.0 in /Users/twang817/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from mdformat-config) (0.10.1)
Requirement already satisfied: mdit-py-plugins<0.4.0,>=0.2.0 in /Users/twang817/.local/lib/python3.8/site-packages (from mdformat-gfm) (0.3.0)
Requirement already satisfied: zipp>=0.5 in /Users/twang817/.local/lib/python3.8/site-packages (from importlib-metadata>=3.6.0->mdformat) (3.8.0)
Requirement already satisfied: mdurl~=0.1 in /Users/twang817/.local/lib/python3.8/site-packages (from markdown-it-py<3.0.0,>=1.0.0b2->mdformat) (0.1.1)
Requirement already satisfied: ruamel.yaml.clib>=0.2.6 in /Users/twang817/.pyenv/versions/3.8.3/lib/python3.8/site-packages (from ruamel.yaml>=0.16.0->mdformat-config) (0.2.6)
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/Users/twang817/.pyenv/versions/3.8.3/bin/python3 -m pip install --upgrade pip' command.
Error: File
"/Users/twang817/workspace/zinit/tests/_support/zunit/plugins/zdharma-continuum---zinit-annex-default-ice/README.md"
is not formatted.
Error: File
"/Users/twang817/workspace/zinit/tests/_support/zunit/plugins/zdharma-continuum---zinit-annex-bin-gem-node/README.md"
is not formatted.
Error: File
"/Users/twang817/workspace/zinit/tests/_support/zunit/zinit.git/README.md" is
not formatted.
Error: File "/Users/twang817/workspace/zinit/README.md" is not formatted.

**Comment by vladdoster** [comment]
You need to remove `--check` so it formats the files

**Comment by vladdoster** [comment]
yeah, I had the same question after I couldn't find the `mkdocs.yml` configuration file. I'll look into this.

However, I am currently working on a complete rework of documentation and plan to have that released this weekend.

**Comment by twang817** [comment]
> You need to remove `--check` so it formats the files

Yeah, I think I finally have this figured out.

**Comment by twang817** [comment]
> yeah, I had the same question after I couldn't find the `mkdocs.yml` configuration file. I'll look into this.

This used to live in the `documentation` branch, which IIRC was an orphan branch.  There was some funkiness in the Makefiles which involved some branch hopping before committing it finally to gh_pages.

**Comment by twang817** [comment]
Gripe.  realpath must not be > 8.23 on the host.

**Comment by vladdoster** [comment]
Can you pull in the latest changes from main? It should fix the labeler workflow.

**Comment by twang817** [comment]
> Before merging, could you explain what the `cache` directory is?

If I've understood your correctly, in a normal snippet, the snippet is downloaded into its directory (under ZINIT[SNIPPETS_DIR]).  The snippet is then read from this directory by zinit.

When using a local directory, this directory serves as a "cache".  The snippet on your local filesystem is copied into the snippet directory where it is read by zinit.  This makes it so that zinit "caches" a copy of your snippet at the time of plugin instead.  This may or may not be desirable.

What this PR does is that instead of copying the local snippet file into your snippet directory, it symlinks it.  Thus, any changes you make to the original file are immediately reflected to zinit.

**Comment by twang817** [comment]
@vladdoster

**Comment by vladdoster** [comment]
@twang817 Merged! Thanks again!! 🥇 💯

**Pull request merged**
