### PR TITLE
add an option to disable aliases

### PR DESCRIPTION
**Pull request by Ryooooooga**
## Description 

Add an option to disable aliases such as `zi` and `zplg`.

## Motivation and Context 

There is a motivation to minimize unnecessary settings.

Especially since zinit has been renamed from zplugin for three years now, zplg is unnecessary for almost everyone.

## Related Issue(s) 

N/A

## Usage examples 

```zsh
# .zshrc
ZINIT[NO_ALIASES]=1
source "${ZINIT[HOME_DIR]}/bin/zinit.zsh"
```

## How Has This Been Tested? 

Rewrote `${ZINIT[HOME_DIR]}/bin/zinit.zsh` and added `ZINIT[NO_ALIASES]=1` before `source`.

## Types of changes 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist: 

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by vladdoster** [comment]
@Ryooooooga, 

Thanks for adding this. Can you add this variable to the README.md?

https://github.com/zdharma-continuum/zinit#customizing-paths

**Comment by vladdoster** [comment]
@Ryooooooga Please rebase `zdharma-continuum/zinit` main branch onto your fork.

**Comment by Ryooooooga** [comment]
I rebased and added the doc.

**Comment by pschmitt** [comment]
Thanks for updating, merging!

**Pull request merged**
