### PR TITLE
Enable developers to build docs in docker

### PR DESCRIPTION
**Pull request by nbrown**
After my struggles to generate the docs such that they pass the documentation check, I used docker to execute ``make doc``.

I also added ``doc-in-docker`` as a target in the Makefile which will build the docker image and generate the docs in the current git clone.

### CODE REVIEW

**Comment by pschmitt** [comment]
Interesting work, though I wonder why not just use the zinit docker image - instead of building a separate one just for generating docs?

https://github.com/zdharma-continuum/zinit/pkgs/container/zinit

**Comment by nbrown** [comment]
> Interesting work, though I wonder why not just use the zinit docker image - instead of building a separate one just for generating docs?
> 
> https://github.com/zdharma-continuum/zinit/pkgs/container/zinit

I tried to use an alpine-based docker, but the musl-based locale I found did not generate the same docs as the documentation github action does. I found that I could match it with a ubuntu-based image.

**Comment by pschmitt** [comment]
The best solution to this problem would IMO be to use the docker container for building the docs in both envs: locally, and in CI.
No more guesswork then.

**Comment by vladdoster** [comment]
Closing in favor of #200

**Pull request closed without merging**
