### PR TITLE
Load annexes from zdharma-continuum repos

### PR DESCRIPTION
**Pull request by mortenscheel**

### CODE REVIEW

**Review by alichtman — APPROVED** [review]

**Comment by alichtman** [comment]
tbh I don't understand annexes but LGTM

**Comment by pschmitt** [comment]
These repos do not exist yet, though. Can someone with access create these?

https://github.com/zdharma-continuum/I_WANT_TO_HELP/issues/7
https://github.com/zdharma-continuum/I_WANT_TO_HELP/issues/8

**Comment by ryaminal** [comment]
> tbh I don't fully understand why annexes exist in zinit but LGTM

Annexes are extensions to zinit, yeah? Are you questioning why they aren't just integrated in the core of zinit?

**Comment by alichtman** [comment]
> Are you questioning why they aren't just integrated in the core of zinit?

No, questioning why they exist at all.

https://github.com/zdharma-continuum/z-a-rust#usage

The example usage:

```bash
# Installs rust and then the `lsd' crate and creates
# the `lsd' shim exposing the binary
zinit ice rustup cargo'!lsd'
zinit load zdharma/null

# Installs rust and then the `exa' crate and creates
# the `ls' shim exposing the `exa' binary
zinit ice rustup cargo'!exa -> ls'
zinit load zdharma/null

# Installs rust and then the `exa' and `lsd' crates
zinit ice rustup cargo'exa;lsd'
zinit load zdharma/null

# Installs rust and then the `exa' and `lsd' crates
# and exposes their binaries by altering $PATH
zinit ice rustup cargo'exa;lsd' as"command" pick"bin/(exa|lsd)"
zinit load zdharma/null

# Installs rust and then the `exa' crate and creates
# its shim with standard error redirected to /dev/null
zinit ice rustup cargo'!E:exa'
zinit load zdharma/null

# Just install rust and make it available globally in the system
zinit ice id-as"rust" wait"0" lucid rustup as"command" \
            pick"bin/rustc" atload="export \
                CARGO_HOME=\$PWD RUSTUP_HOME=\$PWD/rustup"
zinit load zdharma/null

# A little more complex rustup configuration that uses Bin-Gem-Node annex
# and installs the cargo completion provided with rustup, using for-syntax
zinit id-as=rust wait=1 as=null sbin="bin/*" lucid rustup \
    atload="[[ ! -f ${ZINIT[COMPLETIONS_DIR]}/_cargo ]] && zi creinstall rust; \
    export CARGO_HOME=\$PWD RUSTUP_HOME=\$PWD/rustup" for \
        zdharma/null
``` 

The functionality replicated in a single install script:

```bash
curl https://sh.rustup.rs -sSf | sh
rustup
cargo install lsd exa
echo "export PATH=\"$PATH:~/.cargo/bin\"" >> ~/.zshenv 
```

If you're more advanced, you can play with installation paths and XDG defaults, but again, those are one command changes. I dislike how much this plugin complicates "install some programs and put them on my PATH."

**Pull request merged**
