### PR TITLE
Delete single-line.zsh

### PR DESCRIPTION
**Pull request by alichtman**
This file doesn't appear to be used anywhere

### CODE REVIEW

**Comment by pschmitt** [comment]
This file was only added once, never updated. So far so good, but:

```zsh
$ rg single-line.zsh
zinit-install.zsh
678:                command curl --progress-bar -fSL "$url" 2> >($ZINIT[BIN_DIR]/share/single-line.zsh >&2) || return 1
697:                command curl --progress-bar -fSL "$url" 2> >($ZINIT[BIN_DIR]/share/single-line.zsh >&2) || return 1
```

- https://github.com/zdharma-continuum/zinit/blob/62c2bfa788ba84939d88fe741ab48b3d401ec30e/zinit-install.zsh#L678
- https://github.com/zdharma-continuum/zinit/blob/62c2bfa788ba84939d88fe741ab48b3d401ec30e/zinit-install.zsh#L697

**➡️ So, let's keep it around for now :)**
The good news is that it should fairly trivial to move this implementation to zinit's core, since this is more or less  `tr -d '\n'`

<details>
<summary>
git blame
</summary>

- https://github.com/zdharma-continuum/zinit/blame/62c2bfa788ba84939d88fe741ab48b3d401ec30e/share/single-line.zsh
- https://github.com/zdharma-continuum/zinit/blame/62c2bfa788ba84939d88fe741ab48b3d401ec30e/zinit-install.zsh#L678
- https://github.com/zdharma-continuum/zinit/blame/62c2bfa788ba84939d88fe741ab48b3d401ec30e/zinit-install.zsh#L697

```zsh
$ git blame share/single-line.zsh
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200  1) #!/usr/bin/env zsh
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200  2)
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200  3) emulate -R zsh
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200  4) setopt extendedglob warncreateglobal typesetsilent rcquotes noshortloops
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200  5)
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200  6) local zero=$'\0' r=$'\r' n=$'\n' IFS=
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200  7) { command perl -pe 'BEGIN { $|++; $/ = \1 }; tr/\r\n/\n\0/' || \
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200  8) gstdbuf -o0 gtr '\r\n' '\n\0' || \
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200  9) stdbuf -o0 tr '\r\n' '\n\0'; print } 2>/dev/null | \
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200 10)  while read -r line; do
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200 11)      if [[ $line == *$zero* ]]; then
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200 12)          # Unused by cURL (there's no newline after the previous progress bar)
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200 13)          #print -nr -- $r${(l:COLUMNS:: :):-}$r${line##*$zero}
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200 14)          print -nr -- $r${(l:COLUMNS:: :):-}$r${line%$zero}
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200 15)      else
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200 16)          print -nr -- $r${(l:COLUMNS:: :):-}$r${${line//[$r$n]/}%\%*}${${(M)line%\%}:+%}
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200 17)      fi
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200 18)  done
18e95b501 (Sebastian Gniazdowski 2020-06-20 03:02:02 +0200 19) print
```
</details>

**Review by pschmitt — CHANGES_REQUESTED** [review]
ABORT! It is being used! :)

**Comment by alichtman** [comment]
image

**Comment by pschmitt** [comment]
Closing this one then ;)

**Pull request closed without merging**
