### PR TITLE
Enable alternate 'tree' commands for zinit ls

### PR DESCRIPTION
**Pull request by nbrown**
Enable users to specify the zinit ls command via ZINIT[LIST_COMMAND] and
provide default commands for exa and tree. Prefer exa if it is installed.

Addresses issue #170

### CODE REVIEW

**Comment by nbrown** [comment]
I regenerated the docs but am still seeing a failure with the documentation test that I do not understand. Any idea what I need to do to make the test pass?

**Comment by twang817** [comment]
> I regenerated the docs but am still seeing a failure with the documentation test that I do not understand. Any idea what I need to do to make the test pass?

This is causing quite the back-up in PRs.  I took a look and couldn't figure out the root cause.

**Comment by alichtman** [comment]
@pschmitt built that test originally. He would probably know what's up

**Comment by vladdoster** [comment]
Your branch is stale.

Your branch -> https://github.com/zdharma-continuum/zinit/pull/176/files#diff-11de0d6127cc1c21e919c6c97f61842afcf4f35e80621d9837e80ee38459c378R1454

But it was updated yesterday

https://github.com/zdharma-continuum/zinit/pull/184/files#diff-11de0d6127cc1c21e919c6c97f61842afcf4f35e80621d9837e80ee38459c378R1454

image

**Comment by nbrown** [comment]
@vladdoster that wasn't true when this PR first failed the documentation test, but I merged main into this branch and it still fails the documentation test.

**Pull request closed without merging**
